Metrics/LineLength:
  Max: 160
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Lint/EndAlignment:
  AlignWith: variable
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 150 # default was 100.
Style/CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: true
