AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - 'app/models/mentor_meeting.rb'
    - 'app/models/mentor.rb'
    - 'app/controllers/mentoring_controller.rb'

# Rails specific

Rails:
  Enabled: true
Rails/OutputSafety:
  Enabled: false # This disallows .html_safe
Rails/TimeZone:
  Enabled: false # This enforces Time.zone.now
Rails/Date:
  Enabled: false # This enforces Time.zone.today
Rails/HasAndBelongsToMany:
  Enabled: false # This disallows HABTM.

# Project styling

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true
Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
Style/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'spec/**/*_spec.rb'
    - 'config/**/*'
    - 'spec/factories/*'

# Concessions (remove these if possible / appropriate).

Bundler/OrderedGems:
  Enabled: false # we have a ton of gems, grouped arbitrarily. Could be tackled later.
Style/FrozenStringLiteralComment:
  Enabled: false # forces addition of frozen string literal directive to all files. WTF.
Metrics/LineLength:
  Max: 320 # default was 80.
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 500 # default was 100.
Metrics/AbcSize:
  Max: 30 # default is 15.
Style/GuardClause:
  Enabled: false # this thing is annoying, and can lead to not-as-readable code.
