Metrics/LineLength:
  Max: 160
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'app/models/mentor_meeting.rb'
    - 'app/models/mentor.rb'
StringLiterals:
  Enabled: false
Documentation:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/HashSyntax:
  EnforcedStyle: ruby19
Lint/EndAlignment:
  AlignWith: variable
Metrics/MethodLength:
  Max: 20 # default was 10.
Metrics/ClassLength:
  Max: 400 # default was 100.
Style/CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: true
Metrics/AbcSize:
  Max: 30 # default is 15.
