language: ruby

cache: bundler

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
#  - bundle exec rake db:migrate --trace
#  - bundle exec rake db:test:prepare --trace
script:
  - RAILS_ENV=test bundle exec rspec
