sudo: required
language: ruby
cache: bundler
addons:
  postgresql: '9.4'
services:
- postgresql
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
- export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- RAILS_ENV=test xvfb-run -a bundle exec rspec
notifications:
  slack: svlabs:yHBLUeB6YRk600x88YxeonwL
deploy:
  provider: heroku
  app: sv-co
  api_key:
    secure: YvI5115jfYUO0iNMqk5kyxI9FQCXuKlqLvAQ0Q4M5diu7LVGx/M/f0mS+RBpN0vD1Hm1QrTfjSI1SuDuf3UhYS0whl53lcZhAE6VkQlhXhoXbiyAKwysoF1N1VK8vWcVejLKlrO2EkX9cLhcKfuLnMZqjxzsD4jCUWlYhcVjqRs=
