# We don't need sudo, so let's try the container-based infrastructure.
sudo: false

language: ruby

cache: bundler

addons:
  postgresql: "9.4"

services:
  - postgresql

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
#  - bundle exec rake db:migrate --trace
#  - bundle exec rake db:test:prepare --trace
script:
  - RAILS_ENV=test xvfb-run -a bundle exec rspec
