name: Continuous Integration

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      RAILS_ENV: test
      RUBYOPT: '-W:no-deprecated -W:no-experimental'
      JAVASCRIPT_DRIVER: headless_chrome
      DB_HOST: localhost
      DB_NAME_TEST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CAPYBARA_MAX_WAIT_TIME: 5

    steps:
      - name: Setup Timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Kolkata
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Restore Bundle
        uses: actions/cache@master
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Rubocop
        run: bundle exec rubocop
      - name: Setup Database
        run: |
          bundle exec rake db:schema:load
      - name: Restore Assets
        uses: actions/cache@master
        with:
          path: public/assets
          key: ${{ runner.os }}-assets
      - name: Restore Lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            app/javascript/packages/*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Precompile Assets
        run: |
          bundle exec rails assets:precompile
          bundle exec rails assets:clean
      - name: Specs
        run: bundle exec rspec --format progress
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Screenshots
          path: tmp/capybara
