name: Tests

on:
  push:
    branches: ['*']
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build and test with Rake
        env:
          RAILS_ENV: test
          RUBYOPT: '-W:no-deprecated -W:no-experimental'
          JAVASCRIPT_DRIVER: headless_chrome
          DB_HOST: localhost
          DB_NAME_TEST: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          CAPYBARA_MAX_WAIT_TIME: 5
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn
          bundle exec rails db:create
          bundle exec rails db:test:prepare
          bundle exec rails assets:precompile
          bundle exec rspec
